/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniapplication_JniMainApp */

#ifndef _Included_jniapplication_JniMainApp
#define _Included_jniapplication_JniMainApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniapplication_JniMainApp
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jniapplication_JniMainApp_hello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jniapplication_JniMainApp
 * Method:    sayHi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jniapplication_JniMainApp_sayHi
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
